default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin

development:
  <<: *default
  database: storyapp_development
  username: postgres
  password: admin

test:
  <<: *default
  database: storyapp_test
